# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298b4a6a236e6fcdc2402c0ccb6c9fdcdca07faf703dc31a577599e2f98ab204929d667de88581710647bc2ad257c2712433b7ab02d60ded914e3fc9c6e4e506

test:
  secret_key_base: cf5863dde5c7729c6b3b639c8ca9af288f1d7fb9ef73912d633b85e887c60aedd286e938aa9487fdfd72285e865298daae90f2dd73e33dc98a84076bb243686f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
